### PR TITLE
Add fromUser

### PR DESCRIPTION
**Pull request by c4software**
Hi,

I have added the ```fromUser``` parameter to distinguish user-initiated changes from those that occurred programmatically.

### CODE REVIEW

**Comment by c4software** [comment]
Hi,

Do you think it's possible to merge the pull request ?

**Comment by skydoves** [comment]
@c4software 
Hi! Thank you for your PR.
I think distinguishing invoked by user is unusual case.
So I think implementing a new listener with fromUser flag is better choice!

**Comment by c4software** [comment]
Hi,

Not usual ? Its pretty common for instance, look at the SeekBar for example : 

https://developer.android.com/reference/android/widget/SeekBar.OnSeekBarChangeListener

**Comment by skydoves** [comment]
@c4software 
That makes sense.
It will be applied next version.
Thank you for your PR! :)

**Pull request merged**
